language: ruby
sudo: false
cache:
  bundler: true
rvm:
  - 2.5.1
  - 2.4.4
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - RAILS_VERSION=5.2.1
    - RAILS_VERSION=5.1.6
    - RAILS_VERSION=5.0.7
